# Ratio
POSITION_RATIO = 1.8
LOCOMOTION_RATIO = 0.1
LICK_RATIO = 0.1
PUPIL_RATIO = 1
WHISKER_RATIO = 1
FLUORESCENCE_RATIO = 1
TIMELINE_RATIO = 1
RATIO_DICT = {
    "position": POSITION_RATIO,
    "locomotion": LOCOMOTION_RATIO,
    "lick": LICK_RATIO,
    "pupil": PUPIL_RATIO,
    "whisker": WHISKER_RATIO,
    "fluorescence": FLUORESCENCE_RATIO,
    "timeline": TIMELINE_RATIO,
}

# Bin size
LOCOMOTION_BIN_SIZE = 0.2  # s
LICK_BIN_SIZE = 0.2  # s



# Tick 
TIME_TICK_DURATION = 200  # s


# Annotation 
ANNOTATION_OFFSET_FACTOR = 0.1
ANNOTATION_BBOX_HEIGHT_FACTOR = 0.5