# Ratio
POSITION_RATIO = 1.8
LOCOMOTION_RATIO = 0.1
LICK_RATIO = 0.1
PUPIL_RATIO = 1
WHISKER_RATIO = 1

RAW_FLUORESCENCE_RATIO = 0.15
FLUORESCENCE_RATIO = 1

POTENTIAL_RATIO = 1
WC_POTENTIAL_RATIO = 1/15

TIMELINE_RATIO = 1

RATIO_DICT = {
    "position": POSITION_RATIO,
    "locomotion": LOCOMOTION_RATIO,
    "lick": LICK_RATIO,
    "pupil": PUPIL_RATIO,
    "whisker": WHISKER_RATIO,
    "fluorescence": FLUORESCENCE_RATIO,
    "timeline": TIMELINE_RATIO,
}

# Bin size
LOCOMOTION_BIN_SIZE = 0.2  # s
LICK_BIN_SIZE = 0.2  # s



# Tick 
TIME_TICK_DURATION = 200  # s


# Annotation 
ANNOTATION_OFFSET_FACTOR = 0.1
ANNOTATION_BBOX_HEIGHT_FACTOR = 0.5


# Figure params
NORMALIZED_PROGRESS_YLIM = 15
DPI = 1000
FLAT_X_INCHES = 15  # inches
FLAT_Y_INCHES = 2  # inches
UNIT_X_INCHES = 2.5  # inches
UNIT_Y_INCHES = 1.  # inches
PARALLEL_Y_INCHES = 4.5  # inches
ZOOMED_Y_INCHES = 4  # inches
